import { supabase } from './supabase-client.js';

const dayNames = ['LUN', 'MAR', 'MIÉ', 'JUE', 'VIE', 'SÁB', 'DOM'];
const times = ['07:00', '08:00', '09:00', '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00'];
const categoryLabels = {};
const palette = ['#e98269', '#a792d0', '#7f9d7c', '#d2a52e', '#83aabb', '#d48baf', '#7e9ba5', '#bd9b6b', '#8fa978', '#c08066'];
const fixedCategories = { estudio: { name: 'Estudio', color: '#d2a52e' }, gym: { name: 'Gym', color: '#e98269' }, salud: { name: 'Salud', color: '#a792d0' }, otros: { name: 'Otros', color: '#83aabb' } };
let categoryColors = JSON.parse(localStorage.getItem('ritmo-category-colors')) || {};
let customCategories = JSON.parse(localStorage.getItem('ritmo-custom-categories')) || {};
Object.entries(fixedCategories).forEach(([key, category]) => { categoryColors[key] = category.color; categoryLabels[key] = category.name; });
let nameColors = JSON.parse(localStorage.getItem('ritmo-name-colors')) || {};
let semesters = JSON.parse(localStorage.getItem('ritmo-semesters')) || [];
const $ = selector => document.querySelector(selector);

function titleCase(value) { return value.trim().replace(/\b\w/g, letter => letter.toUpperCase()); }
function categoryKey(value) { return value.trim().toLowerCase().replace(/\s+/g, ' '); }
function ensureCategory(value) { const key = categoryKey(value) || 'otros'; if (!categoryColors[key]) categoryColors[key] = fixedCategories[key]?.color || palette.find(color => !Object.values(categoryColors).includes(color)) || palette[Object.keys(categoryColors).length % palette.length]; categoryLabels[key] = fixedCategories[key]?.name || titleCase(value || 'Otros'); if (!fixedCategories[key]) customCategories[key] = { name: categoryLabels[key], color: categoryColors[key] }; return key; }
function ensureNameColor(activity) { const key = `${activity.category}|${activity.name.trim().toLowerCase()}`; if (!nameColors[key]) { let hash = 0; for (const char of key) hash = ((hash << 5) - hash) + char.charCodeAt(0); nameColors[key] = palette[Math.abs(hash) % palette.length]; } return nameColors[key]; }
function migrateActivities(items) { return items.map(activity => { const category = ensureCategory(activity.category || 'personal'); const duration = Number(activity.duration) || 1; const start = activity.horaInicio || '09:00'; const end = activity.horaFin || addMinutes(start, duration * 60); const isMedical = activity.type === 'Procedimiento médico' || activity.id === 'cirugia'; return { ...activity, category, type: isMedical ? 'Procedimiento médico' : 'Actividad', horaInicio: start, horaFin: end, recoveryHours: isMedical ? Number(activity.recoveryHours ?? (activity.recovery || 0) * 24) : 0, prep: 0, duration: undefined }; }); }
const legacyDemoIds = new Set(['dentista', 'entreno', 'clase', 'cirugia', 'proyecto', 'e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7']);
let activities = migrateActivities(JSON.parse(localStorage.getItem('ritmo-activities')) || []);
let events = JSON.parse(localStorage.getItem('ritmo-events')) || [];
activities = activities.filter(activity => !legacyDemoIds.has(activity.id));
events = events.filter(event => !legacyDemoIds.has(event.id) && !legacyDemoIds.has(event.activityId));
events = events.map(event => { if (!event.time || event.horaInicio) return event; const activity = activities.find(item => item.id === event.activityId); const duration = activity ? durationHours(activity) : 1; return { ...event, horaInicio: event.time, horaFin: addMinutes(event.time, duration * 60) }; });
let currentDate = new Date();
let calendarView = 'week';
let editingEventId = null;
let selectedEventId = null;
function persist() { localStorage.setItem('ritmo-activities', JSON.stringify(activities)); localStorage.setItem('ritmo-events', JSON.stringify(events)); localStorage.setItem('ritmo-category-colors', JSON.stringify(categoryColors)); localStorage.setItem('ritmo-custom-categories', JSON.stringify(customCategories)); localStorage.setItem('ritmo-name-colors', JSON.stringify(nameColors)); localStorage.setItem('ritmo-semesters', JSON.stringify(semesters)); }
function parseMinutes(value) { const [hours, minutes] = value.split(':').map(Number); return hours * 60 + minutes; }
function addMinutes(time, amount) { const total = (parseMinutes(time) + amount) % 1440; return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(Math.round(total % 60)).padStart(2, '0')}`; }
function durationHours(activity) { let minutes = parseMinutes(activity.horaFin) - parseMinutes(activity.horaInicio); if (minutes <= 0) minutes += 1440; return minutes / 60; }
function hoursLabel(hours) { const whole = Math.floor(hours); const minutes = Math.round((hours - whole) * 60); return `${whole ? `${whole} h` : ''}${whole && minutes ? ' ' : ''}${minutes ? `${minutes} min` : ''}` || '0 min'; }
function dateWithOffset(dateString, offset) { const date = new Date(`${dateString}T12:00:00`); date.setDate(date.getDate() + offset); return date.toISOString().slice(0, 10); }
function eventDetails(event) { const activity = activities.find(item => item.id === event?.activityId); return { ...event, activity, horaInicio: event?.horaInicio || activity?.horaInicio, horaFin: event?.horaFin || activity?.horaFin }; }
function eventTimestamp(event, end = false) { const detail = eventDetails(event); const time = end ? detail.horaFin : detail.horaInicio; const date = new Date(`${detail.date}T${time}:00`); if (end && parseMinutes(detail.horaFin) <= parseMinutes(detail.horaInicio)) date.setDate(date.getDate() + 1); return date.getTime(); }
function eventEndWithRecovery(event) { return eventTimestamp(event, true) + (eventDetails(event).activity.recoveryHours || 0) * 3600000; }
function recoveryDates(event) { const detail = eventDetails(event); if (!detail.activity || !detail.activity.recoveryHours) return []; const lastDate = new Date(eventEndWithRecovery(event)); const datesBlocked = []; for (let date = new Date(`${detail.date}T12:00:00`); date <= lastDate; date.setDate(date.getDate() + 1)) { const value = date.toISOString().slice(0, 10); if (value !== detail.date) datesBlocked.push(value); } return datesBlocked; }
function conflictsFor(newEvent, activity) { const requested = { ...newEvent, activityId: activity.id }; const start = eventTimestamp(requested); const end = eventTimestamp(requested, true) + (activity.recoveryHours || 0) * 3600000; return events.map(eventDetails).filter(existing => { const existingStart = eventTimestamp(existing); const existingEnd = eventEndWithRecovery(existing); return start < existingEnd && end > existingStart; }); }
function suggestDate(activity, startDate) { for (let offset = 1; offset < 60; offset += 1) { const candidate = { date: dateWithOffset(startDate, offset), horaInicio: activity.horaInicio, horaFin: activity.horaFin }; if (!conflictsFor(candidate, activity).length) return candidate.date; } return null; }
function activeCategories() { return [...document.querySelectorAll('#calendar-filters input:checked')].map(input => input.dataset.filter); }
function eventColor(activity, filteredCategoryCount) { return filteredCategoryCount === 1 ? ensureNameColor(activity) : categoryColors[activity.category]; }
function allCategories() { return [...new Set([...Object.keys(fixedCategories), ...Object.keys(customCategories), ...activities.map(activity => activity.category)])]; }
function renderFilters() { const categories = allCategories(); $('#calendar-filters').innerHTML = categories.map(category => `<label class="check-row"><input type="checkbox" checked data-filter="${category}" /><span class="dot" style="background:${categoryColors[category]}"></span>${categoryLabels[category] || customCategories[category]?.name || titleCase(category)}</label>`).join(''); document.querySelectorAll('#calendar-filters input').forEach(input => input.addEventListener('change', renderCalendar)); }
function localDate(date) { return date.toISOString().slice(0, 10); }
function startOfWeek(date) { const result = new Date(date); const day = result.getDay(); result.setDate(result.getDate() - (day === 0 ? 6 : day - 1)); result.setHours(12, 0, 0, 0); return result; }
function datesForView() { if (calendarView === 'day' || (calendarView === 'week' && window.innerWidth <= 600)) return [localDate(currentDate)]; if (calendarView === 'month') { const first = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1, 12); const count = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0).getDate(); return Array.from({ length: count }, (_, index) => localDate(new Date(first.getFullYear(), first.getMonth(), index + 1, 12))); } const week = startOfWeek(currentDate); return Array.from({ length: 7 }, (_, index) => localDate(new Date(week.getFullYear(), week.getMonth(), week.getDate() + index, 12))); }
function formatDate(dateString, options = { day: '2-digit', month: '2-digit', year: 'numeric' }) { return new Intl.DateTimeFormat('es-ES', options).format(new Date(`${dateString}T12:00:00`)); }
function updateCalendarLabel(viewDates) { const label = $('#week-label'); if (calendarView === 'day' || viewDates.length === 1) label.textContent = formatDate(viewDates[0]); else if (calendarView === 'month') label.textContent = new Intl.DateTimeFormat('es-ES', { month: 'long', year: 'numeric' }).format(currentDate).replace(/^./, letter => letter.toUpperCase()); else label.textContent = `${formatDate(viewDates[0], { day: '2-digit', month: 'short' })} — ${formatDate(viewDates[6], { day: '2-digit', month: 'short', year: 'numeric' })}`; }
function eventMarkup(item, singleCategory) { const color = eventColor(item.activity, singleCategory ? 1 : activeCategories().length); const actions = `<span class="event-actions"><button type="button" data-edit-event="${item.id}" aria-label="Editar">✎</button><button type="button" data-delete-event="${item.id}" aria-label="Eliminar">×</button></span>`; return `<div class="cal-event" style="background:${color};border-left-color:${color}" title="${item.activity.name}" data-event-id="${item.id}">${actions}<strong>${item.activity.name}</strong><small>${item.horaInicio}–${item.horaFin}</small></div>`; }
function renderMonth(viewDates, selected) { const grid = $('#calendar-grid'); grid.className = 'calendar-grid month-grid'; grid.innerHTML = dayNames.map(day => `<div class="month-day-name">${day}</div>`).join(''); const firstDay = new Date(`${viewDates[0]}T12:00:00`).getDay(); const offset = firstDay === 0 ? 6 : firstDay - 1; for (let index = 0; index < offset; index += 1) grid.innerHTML += '<div class="month-cell muted"></div>'; viewDates.forEach(date => { const dayEvents = events.map(eventDetails).filter(event => event.date === date && selected.includes(event.activity.category)); grid.innerHTML += `<div class="month-cell"><strong>${new Date(`${date}T12:00:00`).getDate()}</strong>${dayEvents.slice(0, 3).map(event => `<button class="month-event" data-event-id="${event.id}" style="background:${eventColor(event.activity, selected.length === 1)}">${event.activity.name}</button>`).join('')}${dayEvents.length > 3 ? `<small>+${dayEvents.length - 3} más</small>` : ''}</div>`; }); }
function renderCalendarLegacy() { const grid = $('#calendar-grid'); const selected = activeCategories(); const singleCategory = selected.length === 1; const viewDates = datesForView(); updateCalendarLabel(viewDates); document.querySelectorAll('.view-switcher button').forEach(button => button.classList.toggle('selected', button.dataset.calendarView === calendarView)); if (calendarView === 'month') { renderMonth(viewDates, selected); bindEventActions(); return; } grid.className = 'calendar-grid'; grid.innerHTML = '<div class="day-head"></div>'; viewDates.forEach((date, index) => { const day = new Date(`${date}T12:00:00`).getDate(); grid.innerHTML += `<div class="day-head ${localDate(currentDate) === date ? 'today' : ''}"><span class="day-name">${dayNames[index === undefined ? 0 : (new Date(`${date}T12:00:00`).getDay() + 6) % 7]}</span><strong>${day}</strong></div>`; }); times.forEach(time => { grid.innerHTML += `<div class="time-label">${time}</div>`; viewDates.forEach(date => { const matching = events.map(eventDetails).filter(event => event.date === date && selected.includes(event.activity.category) && event.horaInicio.slice(0, 2) === time.slice(0, 2)); let content = matching.map(item => { const offset = parseMinutes(item.horaInicio) % 60; const height = Math.max(35, durationHours(item.activity) * 75 - 8); return `<div style="top:${offset + 5}px;height:${height}px" class="cal-event-wrap">${eventMarkup(item, singleCategory)}</div>`; }).join(''); const recovery = events.map(eventDetails).find(event => selected.includes(event.activity.category) && recoveryDates(event).includes(date)); if (recovery && !matching.length && time === times[0]) content = '<div class="cal-block">recuperación médica</div>'; grid.innerHTML += `<div class="cal-slot">${content}</div>`; }); }); bindEventActions(); }
function renderActivities() { $('#activity-list').innerHTML = activities.map(activity => { const event = events.find(item => item.activityId === activity.id); return `<article class="activity-card" data-event-id="${event?.id || ''}"><div class="activity-icon" style="background:${categoryColors[activity.category]}22;color:${categoryColors[activity.category]}">${activity.icon || '•'}</div><div class="card-actions">${event ? `<button type="button" data-edit-event="${event.id}" aria-label="Editar actividad">✎</button><button type="button" data-delete-event="${event.id}" aria-label="Eliminar actividad">×</button>` : ''}</div>${activity.type === 'Procedimiento médico' ? '<span class="care-tag">cuidados especiales</span>' : ''}<h3>${activity.name}</h3><p>${activity.notes || `${categoryLabels[activity.category] || titleCase(activity.category)} · ${activity.type}`}</p><div class="activity-meta"><span>${activity.horaInicio}–${activity.horaFin}</span><span>${hoursLabel(durationHours(activity))}</span>${activity.recoveryHours ? `<span>+${hoursLabel(activity.recoveryHours)} recup.</span>` : ''}</div></article>`; }).join(''); bindEventActions(); }
function renderCategoryManager() { const custom = Object.keys(customCategories); $('#category-manager').innerHTML = `<div class="section-heading"><h2>Categorías</h2><span>${Object.keys(fixedCategories).length} fijas · ${custom.length} personalizadas</span></div><div class="category-chips">${allCategories().map(category => `<span class="category-chip"><i style="background:${categoryColors[category]}"></i>${categoryLabels[category] || customCategories[category]?.name || titleCase(category)}${fixedCategories[category] ? '<small>fija</small>' : `<button type="button" data-delete-category="${category}" aria-label="Eliminar categoría">×</button>`}</span>`).join('')}</div>`; document.querySelectorAll('[data-delete-category]').forEach(button => button.addEventListener('click', () => deleteCategory(button.dataset.deleteCategory))); }
function renderSemesters() { $('#semester-list').innerHTML = semesters.map(semester => `<article class="semester-card"><div><p class="eyebrow">${semester.start} → ${semester.end}</p><h3>${semester.name}</h3><p>${semester.subjects.length} materia${semester.subjects.length === 1 ? '' : 's'} · ${semester.subjects.reduce((sum, subject) => sum + subject.blocks.length + subject.labBlocks.length, 0)} bloques semanales</p></div><button class="icon-button" type="button" data-delete-semester="${semester.id}" aria-label="Eliminar semestre">×</button></article>`).join(''); document.querySelectorAll('[data-delete-semester]').forEach(button => button.addEventListener('click', () => deleteSemester(button.dataset.deleteSemester))); }
function availabilityForWeek() { const week = Array.from({ length: 7 }, (_, index) => localDate(new Date(startOfWeek(currentDate).getTime() + index * 86400000))); return week.map(date => { const intervals = events.map(eventDetails).flatMap(event => { if (event.date === date) return [[parseMinutes(event.horaInicio), Math.min(1440, parseMinutes(event.horaFin) + (event.activity.recoveryHours || 0) * 60)]]; if (recoveryDates(event).includes(date)) return [[0, 1440]]; return []; }).sort((a, b) => a[0] - b[0]); const merged = []; intervals.forEach(interval => { const previous = merged[merged.length - 1]; if (previous && interval[0] <= previous[1]) previous[1] = Math.max(previous[1], interval[1]); else merged.push(interval); }); const free = []; let cursor = 0; merged.forEach(([start, end]) => { if (start > cursor) free.push([cursor, start]); cursor = Math.max(cursor, end); }); if (cursor < 1440) free.push([cursor, 1440]); return { date, free }; }); }
function timeLabel(minutes) { return `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`; }
function freeMinutesForWeek() { return availabilityForWeek().reduce((total, item) => total + item.free.reduce((sum, [start, end]) => sum + Math.max(0, end - start), 0), 0); }
function renderAvailability() { $('#availability-list').innerHTML = availabilityForWeek().map(item => `<div class="availability-row"><strong>${formatDate(item.date, { weekday: 'long' })}</strong><span>${item.free.length ? item.free.map(([start, end]) => start === 0 && end === 1440 ? 'libre todo el día' : `libre de ${timeLabel(start)} a ${timeLabel(end)}`).join(' · ') : 'sin espacios libres'}</span></div>`).join(''); }
function renderSummary() { const total = events.reduce((sum, event) => sum + durationHours(eventDetails(event).activity), 0); const freeHours = freeMinutesForWeek() / 60; const blockedDates = new Set(events.flatMap(recoveryDates)); const totals = {}; events.forEach(event => { const activity = eventDetails(event).activity; totals[activity.category] = (totals[activity.category] || 0) + durationHours(activity); }); const max = Math.max(...Object.values(totals), 1); $('#availability-insight').innerHTML = `Tienes <b>${hoursLabel(freeHours)}</b> disponibles para nuevas actividades.`; $('#summary-grid').innerHTML = `<article class="summary-card"><p>Tiempo ocupado</p><div class="summary-value">${hoursLabel(total)}</div><p>en actividades agendadas</p><div class="trend">↗ Calculado con hora de inicio y fin</div></article><article class="summary-card"><p>Tiempo disponible</p><div class="summary-value">${hoursLabel(freeHours)}</div><p>en la semana actual</p><div class="trend">Incluye huecos y recuperación</div></article><article class="summary-card"><p>Días restringidos</p><div class="summary-value">${blockedDates.size}</div><p>por recuperación médica</p><div class="trend">Solo aplica a procedimientos</div></article>`; $('#category-bars').innerHTML = Object.entries(totals).map(([category, hours]) => `<div class="bar-row"><span>${categoryLabels[category] || titleCase(category)}</span><div class="bar-track"><div class="bar-fill" style="width:${hours / max * 100}%;background:${categoryColors[category]}"></div></div><span class="bar-value">${hoursLabel(hours)}</span></div>`).join(''); renderAvailability(); }
function fillCategoryOptions() { $('#activity-category').innerHTML = `<option value="">Sin categoría específica (Otros)</option>${allCategories().map(category => `<option value="${category}">${categoryLabels[category] || customCategories[category]?.name || titleCase(category)}</option>`).join('')}`; }
function recoverySuggestion(kind) { return { 'Procedimiento ambulatorio': 24, 'Cirugía menor': 72, 'Cirugía mayor': 336 }[kind] || 24; }
function updateMedicalFields() { const isMedical = $('#activity-type').value === 'Procedimiento médico'; $('#medical-fields').classList.toggle('visible', isMedical); if (isMedical) $('#recovery-hours').value = recoverySuggestion($('#medical-kind').value); updateDurationPreview(); }
function updateDurationPreview() { const start = $('#activity-start').value; const end = $('#activity-end').value; if (!start || !end) return; const fake = { horaInicio: start, horaFin: end }; $('#duration-preview').textContent = `Duración calculada: ${hoursLabel(durationHours(fake))}${$('#activity-type').value === 'Procedimiento médico' ? ` + ${hoursLabel(Number($('#recovery-hours').value) || 0)} de recuperación` : ''}`; }
function openModal(eventId = null) { editingEventId = eventId; $('#modal-title').textContent = eventId ? 'Editar actividad' : 'Nueva actividad'; $('#modal-backdrop').classList.add('open'); $('#booking-feedback').className = 'booking-feedback'; $('#booking-feedback').textContent = ''; fillCategoryOptions(); if (eventId) { const detail = eventDetails(events.find(event => event.id === eventId)); $('#activity-name').value = detail.activity.name; $('#activity-category').value = detail.activity.category; $('#activity-type').value = detail.activity.type; $('#activity-date').value = detail.date; $('#activity-start').value = detail.horaInicio; $('#activity-end').value = detail.horaFin; $('#recovery-hours').value = detail.activity.recoveryHours || 0; } else { $('#activity-form').reset(); $('#activity-category').value = ''; $('#activity-block-fields').classList.remove('visible'); } updateMedicalFields(); }
function closeModal() { $('#modal-backdrop').classList.remove('open'); }
function scopeForGenerated(action) { return window.prompt(`Esta actividad viene de un bloque semestral. Escribe "solo" para aplicar ${action} a esta ocurrencia o "todo" para aplicar a todas las semanas.`) === 'todo' ? 'all' : 'one'; }
function bindEventActionsLegacy() { document.querySelectorAll('[data-edit-event]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); openModal(button.dataset.editEvent); })); document.querySelectorAll('[data-delete-event]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); deleteEvent(button.dataset.deleteEvent); })); document.querySelectorAll('.month-event').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); openModal(button.dataset.eventId); })); document.querySelectorAll('.cal-event, .activity-card').forEach(element => element.addEventListener('click', event => { if (event.target.closest('button')) return; const id = element.dataset.eventId; if (id) openModal(id); })); }
function deleteEvent(eventId) { const event = events.find(item => item.id === eventId); if (!event) return; const detail = eventDetails(event); const scope = detail.activity.semesterId ? scopeForGenerated('eliminar') : 'one'; if (!window.confirm(`¿Eliminar "${detail.activity.name}"?`)) return; if (scope === 'all') { const blockId = detail.activity.blockId; const ids = new Set(activities.filter(activity => activity.semesterId === detail.activity.semesterId && (!blockId || activity.blockId === blockId)).map(activity => activity.id)); activities = activities.filter(activity => !ids.has(activity.id)); events = events.filter(item => !ids.has(item.activityId)); } else { activities = activities.filter(activity => activity.id !== event.activityId); events = events.filter(item => item.id !== eventId); } persist(); renderAll(); }
function openCategoryModal() { $('#category-modal-backdrop').classList.add('open'); $('#category-feedback').textContent = ''; }
function closeCategoryModal() { $('#category-modal-backdrop').classList.remove('open'); }
function openSemesterModal() { $('#semester-modal-backdrop').classList.add('open'); $('#semester-feedback').textContent = ''; $('#semester-form').reset(); $('#theory-blocks').innerHTML = ''; $('#lab-blocks').classList.remove('visible'); addScheduleBlock('theory'); }
function closeSemesterModal() { $('#semester-modal-backdrop').classList.remove('open'); }
function scheduleBlockMarkup(type, index) { return `<div class="schedule-block" data-block-type="${type}"><label>Día<select class="block-day"><option value="1">Lunes</option><option value="2">Martes</option><option value="3">Miércoles</option><option value="4">Jueves</option><option value="5">Viernes</option><option value="6">Sábado</option><option value="0">Domingo</option></select></label><label>Inicio<input class="block-start" type="time" value="${type === 'theory' ? '08:00' : '12:00'}" required /></label><label>Fin<input class="block-end" type="time" value="${type === 'theory' ? '10:00' : '14:00'}" required /></label>${index > 0 ? '<button class="icon-button remove-block" type="button" aria-label="Eliminar bloque">×</button>' : ''}</div>`; }
function addScheduleBlock(type) { const container = type === 'theory' ? $('#theory-blocks') : $('#lab-blocks'); const index = container.querySelectorAll('.schedule-block').length; container.insertAdjacentHTML('beforeend', scheduleBlockMarkup(type, index)); container.querySelectorAll('.remove-block').forEach(button => button.addEventListener('click', () => button.closest('.schedule-block').remove())); }
function readScheduleBlocks(selector) { return [...document.querySelectorAll(`${selector} .schedule-block`)].map(block => ({ day: Number(block.querySelector('.block-day').value), start: block.querySelector('.block-start').value, end: block.querySelector('.block-end').value })); }
function semesterDates(start, end, weekday) { const result = []; for (let date = new Date(`${start}T12:00:00`); date.toISOString().slice(0, 10) <= end; date.setDate(date.getDate() + 1)) if (date.getDay() === weekday) result.push(date.toISOString().slice(0, 10)); return result; }
function generateOtherBlock(data) { const start = $('#activity-block-start').value || $('#activity-date').value; const end = $('#activity-block-end').value || start; const weekdays = [...document.querySelectorAll('#activity-block-fields .weekday-picker input:checked')].map(input => Number(input.value)); if (start > end || !weekdays.length) return 0; const blockId = `other-block-${Date.now()}`; const generated = []; weekdays.forEach(day => semesterDates(start, end, day).forEach(date => generated.push({ date, day }))); if (generated.some(item => events.some(existing => { const detail = eventDetails(existing); return detail.date === item.date && data.horaInicio < detail.horaFin && data.horaFin > detail.horaInicio; }))) return -1; generated.forEach((item, index) => { const activityId = `activity-${Date.now()}-${index}`; activities.push({ id: activityId, ...data, icon: '•', notes: 'Otros · bloque recurrente', blockId, care: false }); events.push({ id: `event-${Date.now()}-${index}`, activityId, date: item.date, horaInicio: data.horaInicio, horaFin: data.horaFin, blockId }); }); return generated.length; }
function generateSubjectOccurrences(semester, subject) { const blocks = [...subject.blocks.map(block => ({ ...block, kind: 'Teoría' })), ...subject.labBlocks.map(block => ({ ...block, kind: 'Laboratorio' }))]; let generated = 0; blocks.forEach(block => { const blockId = `${subject.id}-${block.kind}-${block.day}-${block.start}-${block.end}`; semesterDates(semester.start, semester.end, block.day).forEach(date => { const activity = { id: `activity-${Date.now()}-${generated}`, name: `${subject.name} · ${block.kind}`, category: 'estudio', type: 'Actividad', horaInicio: block.start, horaFin: block.end, recoveryHours: 0, icon: block.kind === 'Laboratorio' ? '⌬' : 'A', notes: `${semester.name} · ${block.kind}`, semesterId: semester.id, subjectId: subject.id, blockId, care: false }; const event = { id: `event-${Date.now()}-${generated}`, activityId: activity.id, date, horaInicio: block.start, horaFin: block.end, semesterId: semester.id, subjectId: subject.id, blockId }; activities.push(activity); events.push(event); generated += 1; }); }); return generated; }
function deleteCategory(category) { if (fixedCategories[category]) return; const linked = activities.filter(activity => activity.category === category).length; if (!window.confirm(`Esto eliminará también ${linked} actividades asociadas. ¿Continuar?`)) return; const ids = new Set(activities.filter(activity => activity.category === category).map(activity => activity.id)); activities = activities.filter(activity => activity.category !== category); events = events.filter(event => !ids.has(event.activityId)); delete customCategories[category]; delete categoryColors[category]; delete categoryLabels[category]; persist(); renderAll(); }
function deleteSemester(id) { const semester = semesters.find(item => item.id === id); if (!semester || !window.confirm(`Esto eliminará el semestre y todas sus materias y ocurrencias. ¿Continuar?`)) return; const ids = new Set(activities.filter(activity => activity.semesterId === id).map(activity => activity.id)); activities = activities.filter(activity => activity.semesterId !== id); events = events.filter(event => !ids.has(event.activityId)); semesters = semesters.filter(item => item.id !== id); persist(); renderAll(); }
$('#activity-form').addEventListener('submit', event => { event.preventDefault(); const category = ensureCategory($('#activity-category').value); const type = $('#activity-type').value; const data = { name: $('#activity-name').value.trim(), category, type, horaInicio: $('#activity-start').value, horaFin: $('#activity-end').value, recoveryHours: type === 'Procedimiento médico' ? Number($('#recovery-hours').value) || 0 : 0 }; if (data.horaInicio === data.horaFin) { $('#booking-feedback').className = 'booking-feedback error'; $('#booking-feedback').textContent = 'La hora de fin debe ser distinta a la hora de inicio.'; return; } if (editingEventId) { const target = events.find(item => item.id === editingEventId); const current = eventDetails(target); const scope = current.activity.semesterId ? scopeForGenerated('editar') : 'one'; const matches = scope === 'all' ? events.filter(item => { const detail = eventDetails(item); return detail.activity.semesterId === current.activity.semesterId && detail.activity.blockId === current.activity.blockId; }) : [target]; matches.forEach(item => { const activity = activities.find(entry => entry.id === item.activityId); Object.assign(activity, data, { notes: `${categoryLabels[category]} · ${type}`, icon: type === 'Procedimiento médico' ? '♡' : (activity.icon || '•'), care: type === 'Procedimiento médico' }); Object.assign(item, { date: scope === 'all' ? item.date : $('#activity-date').value, horaInicio: data.horaInicio, horaFin: data.horaFin }); }); persist(); renderAll(); closeModal(); return; } const activity = { id: `activity-${Date.now()}`, ...data, medicalKind: type === 'Procedimiento médico' ? $('#medical-kind').value : '', icon: type === 'Procedimiento médico' ? '♡' : '•', notes: `${categoryLabels[category]} · ${type}`, care: type === 'Procedimiento médico' }; const newEvent = { id: `e${Date.now()}`, activityId: activity.id, date: $('#activity-date').value, horaInicio: activity.horaInicio, horaFin: activity.horaFin }; const conflicts = conflictsFor(newEvent, activity); if (conflicts.length) { const suggestion = suggestDate(activity, newEvent.date); $('#booking-feedback').className = 'booking-feedback error'; $('#booking-feedback').innerHTML = `<strong>No hay espacio suficiente.</strong> Se cruza con ${conflicts[0].activity.name}. La fecha libre más cercana es <b>${suggestion || 'más adelante'}</b>.`; return; } activities.push(activity); events.push(newEvent); ensureNameColor(activity); persist(); renderAll(); $('#booking-feedback').className = 'booking-feedback success'; $('#booking-feedback').innerHTML = '<strong>Actividad agendada.</strong> El tiempo asociado quedó reservado en tu calendario.'; setTimeout(closeModal, 1500); });
$('#category-form').addEventListener('submit', event => { event.preventDefault(); const name = $('#new-category-name').value.trim(); const key = categoryKey(name); if (!name || fixedCategories[key] || customCategories[key]) { $('#category-feedback').className = 'booking-feedback error'; $('#category-feedback').textContent = 'Esa categoría ya existe o no es válida.'; return; } categoryColors[key] = $('#new-category-color').value; categoryLabels[key] = titleCase(name); customCategories[key] = { name: categoryLabels[key], color: categoryColors[key] }; persist(); renderAll(); closeCategoryModal(); });
$('#semester-form').addEventListener('submit', event => { event.preventDefault(); const semester = { id: `semester-${Date.now()}`, name: $('#semester-name').value.trim(), start: $('#semester-start').value, end: $('#semester-end').value, subjects: [] }; const subject = { id: `subject-${Date.now()}`, name: $('#subject-name').value.trim(), blocks: readScheduleBlocks('#theory-blocks'), labBlocks: $('#has-lab').value === 'si' ? readScheduleBlocks('#lab-blocks') : [] }; if (!semester.name || !subject.name || semester.start > semester.end || !subject.blocks.length) { $('#semester-feedback').className = 'booking-feedback error'; $('#semester-feedback').textContent = 'Completa el semestre, la materia y al menos un bloque de teoría.'; return; } semester.subjects.push(subject); const generated = generateSubjectOccurrences(semester, subject); semesters.push(semester); persist(); renderAll(); $('#semester-feedback').className = 'booking-feedback success'; $('#semester-feedback').textContent = `Materia guardada: ${generated} ocurrencias generadas.`; setTimeout(closeSemesterModal, 1200); });
$('#activity-type').addEventListener('change', updateMedicalFields); $('#medical-kind').addEventListener('change', updateMedicalFields); $('#recovery-hours').addEventListener('input', updateDurationPreview); $('#activity-start').addEventListener('input', updateDurationPreview); $('#activity-end').addEventListener('input', updateDurationPreview); $('#open-modal').addEventListener('click', () => openModal()); $('#open-modal-activities').addEventListener('click', () => openModal()); $('#close-modal').addEventListener('click', closeModal); $('#modal-backdrop').addEventListener('click', event => { if (event.target.id === 'modal-backdrop') closeModal(); });
$('#open-category-modal').addEventListener('click', openCategoryModal); $('#close-category-modal').addEventListener('click', closeCategoryModal); $('#category-modal-backdrop').addEventListener('click', event => { if (event.target.id === 'category-modal-backdrop') closeCategoryModal(); }); $('#open-semester-modal').addEventListener('click', openSemesterModal); $('#close-semester-modal').addEventListener('click', closeSemesterModal); $('#semester-modal-backdrop').addEventListener('click', event => { if (event.target.id === 'semester-modal-backdrop') closeSemesterModal(); }); $('#add-subject-block').addEventListener('click', () => addScheduleBlock('theory')); $('#add-lab-block').addEventListener('click', () => addScheduleBlock('lab')); $('#has-lab').addEventListener('change', () => { const enabled = $('#has-lab').value === 'si'; $('#lab-blocks').classList.toggle('visible', enabled); if (enabled && !$('#lab-blocks .schedule-block')) addScheduleBlock('lab'); });
$('#activity-form').addEventListener('submit', event => { if (editingEventId || $('#activity-category').value !== '' || !$('#activity-block-toggle').checked) return; event.preventDefault(); event.stopImmediatePropagation(); const data = { name: $('#activity-name').value.trim(), category: 'otros', type: $('#activity-type').value, horaInicio: $('#activity-start').value, horaFin: $('#activity-end').value, recoveryHours: 0 }; const generated = generateOtherBlock(data); if (generated < 0) { $('#booking-feedback').className = 'booking-feedback error'; $('#booking-feedback').textContent = 'El bloque se cruza con una actividad existente.'; return; } if (!generated) { $('#booking-feedback').className = 'booking-feedback error'; $('#booking-feedback').textContent = 'Selecciona al menos un día y un rango válido.'; return; } persist(); renderAll(); $('#booking-feedback').className = 'booking-feedback success'; $('#booking-feedback').textContent = `Se generaron ${generated} ocurrencias del bloque.`; setTimeout(closeModal, 1200); }, true);
$('#open-category-sidebar').addEventListener('click', openCategoryModal); $('#activity-block-toggle').addEventListener('change', () => { $('#activity-block-fields').classList.toggle('visible', $('#activity-block-toggle').checked); if ($('#activity-block-toggle').checked) { $('#activity-block-start').value = $('#activity-date').value; $('#activity-block-end').value = $('#activity-date').value; } });
function changePeriod(amount) { if (calendarView === 'day') currentDate.setDate(currentDate.getDate() + amount); else if (calendarView === 'month') currentDate.setMonth(currentDate.getMonth() + amount); else currentDate.setDate(currentDate.getDate() + amount * 7); renderCalendar(); }
document.querySelectorAll('.view-switcher button').forEach(button => button.addEventListener('click', () => { calendarView = button.dataset.calendarView; renderCalendar(); }));
$('#previous-period').addEventListener('click', () => changePeriod(-1)); $('#next-period').addEventListener('click', () => changePeriod(1)); $('#go-today').addEventListener('click', () => { currentDate = new Date(); renderCalendar(); }); $('#show-availability').addEventListener('click', () => $('#availability-panel').scrollIntoView({ behavior: 'smooth' }));
function renderAll() { renderFilters(); renderCalendar(); renderActivities(); renderSummary(); renderCategoryManager(); renderSemesters(); fillCategoryOptions(); }
document.querySelectorAll('.nav-item').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('.nav-item').forEach(item => item.classList.remove('active')); button.classList.add('active'); document.querySelectorAll('.view').forEach(view => view.classList.remove('active-view')); $(`#${button.dataset.view}-view`).classList.add('active-view'); $('#page-label').textContent = button.dataset.view === 'agenda' ? 'Esta semana' : button.textContent.trim(); }));
renderAll();

let authMode = 'login';
function setAuthMessage(message, type = '') { const element = $('#auth-message'); element.textContent = message; element.className = `auth-message ${type}`; }
function setAuthenticated(user) { const isAuthenticated = Boolean(user); $('#auth-screen').style.display = isAuthenticated ? 'none' : 'grid'; $('#app-shell').classList.toggle('auth-hidden', !isAuthenticated); if (user?.email) { const initials = user.email.slice(0, 2).toUpperCase(); $('#user-avatar').textContent = initials; } }
function renderAuthMode() { const register = authMode === 'register'; $('#auth-eyebrow').textContent = register ? 'Crear tu espacio' : 'Tu agenda, contigo.'; $('#auth-title').textContent = register ? 'Crea tu cuenta' : 'Bienvenido a Ritmo'; $('#auth-copy').textContent = register ? 'Guarda tu agenda en la nube y consúltala desde cualquier dispositivo.' : 'Inicia sesión para acceder a tu agenda y mantenerla sincronizada entre tus dispositivos.'; $('#auth-submit').innerHTML = register ? 'Crear cuenta <span>→</span>' : 'Iniciar sesión <span>→</span>'; $('#auth-switch').textContent = register ? '¿Ya tienes cuenta? Iniciar sesión' : '¿No tienes cuenta? Crear una'; $('#auth-password').autocomplete = register ? 'new-password' : 'current-password'; setAuthMessage(''); }
$('#auth-switch').addEventListener('click', () => { authMode = authMode === 'login' ? 'register' : 'login'; renderAuthMode(); });
$('#auth-forgot').addEventListener('click', async () => { const email = $('#auth-email').value.trim(); if (!email) { setAuthMessage('Escribe tu correo para recibir el enlace de recuperación.', 'error'); return; } const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/` }); setAuthMessage(error ? error.message : 'Revisa tu correo para restablecer la contraseña.', error ? 'error' : 'success'); });
$('#auth-form').addEventListener('submit', async event => { event.preventDefault(); const email = $('#auth-email').value.trim(); const password = $('#auth-password').value; const button = $('#auth-submit'); button.disabled = true; setAuthMessage('Conectando...'); const result = authMode === 'register' ? await supabase.auth.signUp({ email, password }) : await supabase.auth.signInWithPassword({ email, password }); button.disabled = false; if (result.error) { setAuthMessage(result.error.message, 'error'); return; } if (authMode === 'register' && !result.data.session) { setAuthMessage('Cuenta creada. Revisa tu correo para confirmar el acceso.', 'success'); return; } setAuthenticated(result.data.session?.user); });
$('#logout-button').addEventListener('click', async () => { await supabase.auth.signOut(); setAuthenticated(null); });
supabase.auth.onAuthStateChange((_event, session) => setAuthenticated(session?.user || null));
supabase.auth.getSession().then(({ data }) => setAuthenticated(data.session?.user || null));
renderAuthMode();

function timeOptions(selected = '09:00') { const options = []; for (let minutes = 0; minutes < 1440; minutes += 15) { const value = `${String(Math.floor(minutes / 60)).padStart(2, '0')}:${String(minutes % 60).padStart(2, '0')}`; options.push(`<option value="${value}" ${value === selected ? 'selected' : ''}>${value}</option>`); } return options.join(''); }
function replaceTimeInput(id) { const input = document.getElementById(id); if (!input || input.dataset.timePicker === 'true') return; const select = document.createElement('select'); select.id = id; select.required = input.required; select.className = 'time-select'; select.innerHTML = timeOptions(input.value || '09:00'); input.replaceWith(select); }
function replaceScheduleTimeInputs() { document.querySelectorAll('.block-start, .block-end').forEach(input => { if (input.tagName === 'SELECT') return; const select = document.createElement('select'); select.className = input.className; select.required = input.required; select.innerHTML = timeOptions(input.value || '08:00'); input.replaceWith(select); }); }
function installTimePickers() { replaceTimeInput('activity-start'); replaceTimeInput('activity-end'); replaceScheduleTimeInputs(); ['activity-start', 'activity-end'].forEach(id => document.getElementById(id)?.addEventListener('change', updateDurationPreview)); }
installTimePickers();

const originalAddScheduleBlock = addScheduleBlock;
addScheduleBlock = function(type) { originalAddScheduleBlock(type); replaceScheduleTimeInputs(); };
function renderActivitiesByDay() { const groups = {}; events.map(eventDetails).filter(event => event.activity).sort((first, second) => `${first.date}${first.horaInicio}`.localeCompare(`${second.date}${second.horaInicio}`)).forEach(event => { (groups[event.date] ||= []).push(event); }); $('#activity-list').innerHTML = Object.entries(groups).map(([date, dayEvents]) => `<section class="day-activity-group"><h2>${formatDate(date, { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' })}</h2>${dayEvents.map(event => `<article class="day-activity-item activity-card" data-event-id="${event.id}"><i class="category-dot" style="background:${categoryColors[event.activity.category]}"></i><div><strong>${event.activity.name}</strong><small>${categoryLabels[event.activity.category] || titleCase(event.activity.category)} · ${event.horaInicio}–${event.horaFin}</small></div><div class="card-actions"><button type="button" data-edit-event="${event.id}" aria-label="Editar actividad">✎</button><button type="button" data-delete-event="${event.id}" aria-label="Eliminar actividad">×</button></div></article>`).join('')}</section>`).join(''); bindEventActions(); }
renderActivities = renderActivitiesByDay;
function renderCurrentTimeLine() { document.querySelector('.now-line')?.remove(); if (calendarView === 'month') return; const now = new Date(); const today = localDate(now); const viewDates = datesForView(); const dayIndex = viewDates.indexOf(today); if (dayIndex < 0) return; const minutes = now.getHours() * 60 + now.getMinutes(); const grid = $('#calendar-grid'); const width = 100 / viewDates.length; const line = document.createElement('div'); line.className = 'now-line'; line.style.top = `${58 + minutes / 60 * 75}px`; line.style.left = `calc(52px + (100% - 52px) * ${dayIndex / viewDates.length})`; line.style.width = `calc((100% - 52px) * ${1 / viewDates.length})`; grid.appendChild(line); const card = $('.calendar-card'); if (card && !card.dataset.initialScrolled) { card.scrollTop = Math.max(0, minutes / 60 * 75 - 140); card.dataset.initialScrolled = 'true'; } }
const renderedCalendar = renderCalendar;
renderCalendar = function() { renderedCalendar(); renderCurrentTimeLine(); };
setInterval(renderCurrentTimeLine, 60000);
document.querySelectorAll('.view-switcher button').forEach(button => button.addEventListener('click', () => { $('.calendar-card').dataset.initialScrolled = ''; }, true));

let pendingDeleteId = null;
function closeDeleteConfirm() { $('#delete-confirm-backdrop').classList.remove('open'); pendingDeleteId = null; }
function requestDeleteEvent(eventId) { const event = events.find(item => item.id === eventId); const detail = eventDetails(event); if (!event || !detail.activity) return; pendingDeleteId = eventId; $('#delete-confirm-title').textContent = `¿Eliminar "${detail.activity.name}"?`; $('#delete-confirm-copy').textContent = 'Esta acción no se puede deshacer.'; const isBlock = Boolean(detail.activity.blockId || detail.activity.semesterId); $('#delete-scope').classList.toggle('visible', isBlock); $('#delete-confirm-backdrop').classList.add('open'); }
deleteEvent = requestDeleteEvent;
$('#cancel-delete').addEventListener('click', closeDeleteConfirm); $('#cancel-delete-x').addEventListener('click', closeDeleteConfirm); $('#delete-confirm-backdrop').addEventListener('click', event => { if (event.target.id === 'delete-confirm-backdrop') closeDeleteConfirm(); }); $('#confirm-delete').addEventListener('click', () => { const event = events.find(item => item.id === pendingDeleteId); const detail = eventDetails(event); if (!event || !detail.activity) return; const scope = detail.activity.blockId || detail.activity.semesterId ? document.querySelector('input[name="delete-scope"]:checked').value : 'one'; if (scope === 'all') { const ids = new Set(activities.filter(activity => (detail.activity.semesterId && activity.semesterId === detail.activity.semesterId && activity.blockId === detail.activity.blockId) || (!detail.activity.semesterId && activity.blockId === detail.activity.blockId)).map(activity => activity.id)); activities = activities.filter(activity => !ids.has(activity.id)); events = events.filter(item => !ids.has(item.activityId)); } else { activities = activities.filter(activity => activity.id !== event.activityId); events = events.filter(item => item.id !== pendingDeleteId); } persist(); closeDeleteConfirm(); renderAll(); });
renderAll();

// Calendario preciso: una celda por hora, eventos posicionados por minuto y columnas para solapes.
function eventOverlaps(first, second) { return eventTimestamp(first) < eventTimestamp(second, true) && eventTimestamp(second) < eventTimestamp(first, true); }
function eventLayout(event, dayEvents) { const overlaps = dayEvents.filter(other => other.id !== event.id && eventOverlaps(event, other)); const group = [event, ...overlaps].sort((first, second) => eventTimestamp(first) - eventTimestamp(second)); const index = Math.max(0, group.findIndex(item => item.id === event.id)); return { index, total: Math.max(1, group.length) }; }
function showEventDetail(eventId) { const event = events.find(item => item.id === eventId); const detail = eventDetails(event); if (!event || !detail.activity) return; selectedEventId = eventId; $('#event-detail-title').textContent = detail.activity.name; $('#event-detail-meta').innerHTML = `<div><strong>Categoría:</strong> ${categoryLabels[detail.activity.category] || titleCase(detail.activity.category)}</div><div><strong>Horario:</strong> ${detail.horaInicio}–${detail.horaFin}</div><div><strong>Fecha:</strong> ${formatDate(detail.date)}</div><div><strong>Notas:</strong> ${detail.activity.notes || 'Sin notas'}</div>${detail.activity.type === 'Procedimiento médico' ? `<div><strong>Cuidados especiales:</strong> recuperación de ${hoursLabel(detail.activity.recoveryHours || 0)}</div>` : ''}`; $('#event-detail-backdrop').classList.add('open'); }
function closeEventDetail() { $('#event-detail-backdrop').classList.remove('open'); selectedEventId = null; }
function bindEventActions() { document.querySelectorAll('[data-edit-event]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); openModal(button.dataset.editEvent); })); document.querySelectorAll('[data-delete-event]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); deleteEvent(button.dataset.deleteEvent); })); document.querySelectorAll('.month-event').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); showEventDetail(button.dataset.eventId); })); document.querySelectorAll('.cal-event, .activity-card').forEach(element => element.addEventListener('click', event => { if (event.target.closest('button')) return; const id = element.dataset.eventId; if (id) showEventDetail(id); })); }
function renderCalendar() { const grid = $('#calendar-grid'); const selected = activeCategories(); const singleCategory = selected.length === 1; const viewDates = datesForView(); updateCalendarLabel(viewDates); document.querySelectorAll('.view-switcher button').forEach(button => button.classList.toggle('selected', button.dataset.calendarView === calendarView)); if (calendarView === 'month') { renderMonth(viewDates, selected); bindEventActions(); return; } grid.className = 'calendar-grid'; grid.innerHTML = '<div class="day-head"></div>'; viewDates.forEach(date => { const day = new Date(`${date}T12:00:00`); const dayIndex = (day.getDay() + 6) % 7; grid.innerHTML += `<div class="day-head ${localDate(currentDate) === date ? 'today' : ''}"><span class="day-name">${dayNames[dayIndex]}</span><strong>${day.getDate()}</strong></div>`; }); for (let hour = 0; hour < 24; hour += 1) { const time = `${String(hour).padStart(2, '0')}:00`; grid.innerHTML += `<div class="time-label">${time}</div>`; viewDates.forEach(date => { const dayEvents = events.map(eventDetails).filter(event => event.activity && event.date === date && selected.includes(event.activity.category)); const matching = dayEvents.filter(event => event.horaInicio.slice(0, 2) === String(hour).padStart(2, '0')); const content = matching.map(item => { const offset = parseMinutes(item.horaInicio) % 60; const height = Math.max(28, durationHours(item.activity) * 75 - 6); const layout = eventLayout(item, dayEvents); const color = eventColor(item.activity, singleCategory ? 1 : selected.length); return `<div class="cal-event-wrap" style="top:${offset}px;height:${height}px;left:calc(${layout.index} * ${100 / layout.total}%);width:calc(${100 / layout.total}% - 4px)"><div class="cal-event" style="background:${color};border-left-color:${color}" title="${item.activity.name}" data-event-id="${item.id}"><strong>${item.activity.name}</strong><small>${item.horaInicio}–${item.horaFin}</small></div></div>`; }).join(''); const recovery = dayEvents.find(event => recoveryDates(event).includes(date)); grid.innerHTML += `<div class="cal-slot">${content || (recovery && hour === 0 ? '<div class="cal-block">recuperación médica</div>' : '')}</div>`; }); } bindEventActions(); }
$('#close-event-detail').addEventListener('click', closeEventDetail); $('#event-detail-backdrop').addEventListener('click', event => { if (event.target.id === 'event-detail-backdrop') closeEventDetail(); }); $('#edit-event-detail').addEventListener('click', () => { const eventId = selectedEventId; closeEventDetail(); if (eventId) openModal(eventId); }); $('#delete-event-detail').addEventListener('click', () => { const eventId = selectedEventId; closeEventDetail(); if (eventId) deleteEvent(eventId); }); $('.insight-action').addEventListener('click', () => { document.querySelector('[data-view="resumen"]').click(); setTimeout(() => $('#availability-panel').scrollIntoView({ behavior: 'smooth' }), 0); });
renderAll();
